name: Build and Deploy with Packer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOT_PATH : '${{github.workspace}}/windows'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Packer image
      working-directory: ${{env.ROOT_PATH}}
      run: |
        packer init .
        packer build .
