name: Build and Deploy with Packer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOT_PATH : '${{github.workspace}}/windows'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build Packer image
      run: |
        packer init .
        packer build .
